name: sudoku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  sudoku_dart: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
